from .experiment import DEFINITION as EXPERIMENT_DEFINITION
from .join import DEFINITION as JOIN_DEFINITION
from .multichoice import DEFINITION as MULTICHOICE_DEFINITION
from .player import DEFINITION as PLAYER_DEFINITION
from .pressure import DEFINITION as PRESSURE_DEFINITION
from .sound import DEFINITION as SOUND_DEFINITION
from .spectrum import DEFINITION as SPECTRUM_DEFINITION
from .timer import DEFINITION as TIMER_DEFINITION
from .webcam import DEFINITION as WEBCAM_DEFINITION

__all__ = [
  "EXPERIMENT_DEFINITION",
  "JOIN_DEFINITION",
  "MULTICHOICE_DEFINITION",
  "PLAYER_DEFINITION",
  "PRESSURE_DEFINITION",
  "SOUND_DEFINITION",
  "SPECTRUM_DEFINITION",
  "TIMER_DEFINITION",
  "WEBCAM_DEFINITION",
]
